### ISSUE TITLE
Confusion between commands and flags

### ISSUE THREAD

**Issue by jlengrand** [RamonGebben/mergify#29]
At the moment, the project uses flags([options](https://github.com/tj/commander.js/#option-parsing)) to issues commands `mergify -v`, ...

Flags should be more used for options (for example to disable certificates verification, . . .).

[Commands](https://github.com/tj/commander.js/#command-specific-options) seem more relevant for things like submitted / review,  . . .

For exampple, something like

`$ mergify configure -s` sounds more logical than `mergify -sc`.

In addition, commands could have autocompletion.

**Comment by jlengrand** [comment]
Seems like this would also allow us to provide default commands \o/

**Comment by RamonGebben** [comment]
@jlengrand you can check the commander.js docs for "Gitstyle" CLI. Concerning the default command it's already taken care of, the default command shows the help message.

**Comment by jlengrand** [comment]
@RamonGebben I agree it's already taken care of. But wouldn't you prefer `mergify` to directly run the equivalent of `mergify submitted`?
