### ISSUE TITLE
The documentation mentions to create an auth token. But I don't know if read access is enough.

### ISSUE THREAD

**Issue by jlengrand** [RamonGebben/mergify#9]
I don't really want to give you write access if I don't have to :).

<img width="678" alt="screen shot 2018-04-18 at 9 56 12 am" src="https://user-images.githubusercontent.com/921666/38918695-c7494be2-42ee-11e8-91ce-39309e4badb3.png">

**Comment by RamonGebben** [comment]
Read access should be enough but indeed the documentation should inform users about this.

**Comment by jlengrand** [comment]
This is the rights that we need : 

<img width="603" alt="screen shot 2018-04-19 at 9 25 42 am" src="https://user-images.githubusercontent.com/921666/38989043-c9c04b22-43d5-11e8-8c7b-d05e3001bf1a.png">

**Comment by jlengrand** [comment]
And this is where to find your user id

<img width="1208" alt="screen shot 2018-04-19 at 1 33 53 pm" src="https://user-images.githubusercontent.com/921666/38989234-6d7ff064-43d6-11e8-8758-f90bddf7dbe5.png">

**Comment by jlengrand** [comment]
I made https://github.com/RamonGebben/mergify/pull/14 to fix this @RamonGebben

**Comment by jlengrand** [comment]
API access is actually required. Just tested with read only.

<img width="611" alt="screen shot 2018-04-20 at 1 09 40 pm" src="https://user-images.githubusercontent.com/921666/39047997-4022dfa2-449c-11e8-9bec-12039ad94d94.png">
